### ISSUE TITLE
openhab2 incorrectly does not depend on java

### ISSUE THREAD

**Issue by RREE** [openhab/openhab-linuxpkg#79] opened 2017-08-29 22:05 UTC
I could install openhab2 on a raspian (Jessie) system without previous installation of any java runtime.

I created /etc/apt/sources.list.d/openhab2.list with the following contents:
deb https://dl.bintray.com/openhab/apt-repo2 stable main
$ aptitude update
$ aptitude install openhab2
worked without any mention of java.

Only when looking into journalctl I saw the following lines:
Aug 28 21:15:51 z3 start.sh[524]: /usr/share/openhab2/runtime/bin/setenv: line 176: type: java: not found
Aug 28 21:15:51 z3 start.sh[524]: /usr/share/openhab2/runtime/bin/setenv: line 179: die: command not found

This was issue #526, https://github.com/openhab/openhab-distro/issues/526

**Comment by BClark09** [comment] 2017-08-29 23:59
Hi @RREE, did you see my reply to the comment:

>Please note that for the later versions of openHAB, apt will now recommend Java.
>
>We cannot depend on it via a package manager as there are many different ways of including it. For example, via manual extraction, or by installing either or multiples of Zulu/Oracle/open JDK.

**Comment by ThomDietrich** [comment] 2017-08-30 10:57
@BClark09 the second part of the issue is something wort looking into, right?

**Comment by BClark09** [comment] 2017-08-30 11:02
Ah yes, but this should be resolved for 2.2 and it's current snapshots from https://github.com/openhab/openhab-distro/pull/496

**Comment by ThomDietrich** [comment] 2017-08-30 11:09
Hmmm if I'm not mistaken, that is yes for `die: command not` but no for `type: java: not found`

https://github.com/openhab/openhab-distro/blob/master/distributions/openhab/src/main/resources/bin/setenv#L182

https://stackoverflow.com/a/677212

**Comment by ThomDietrich** [comment] 2017-08-30 11:12
I'm not even sure what the whole block is for. Wouldn't that be enough:

```shell
command -v java >/dev/null 2>&1 || die "java command not found"
```

**Comment by BClark09** [comment] 2017-08-30 11:39
To be honest, not at all sure why it was written like that. The function is written from KARAF. But it looks like they also agree with you now ;) The version of KARAF that openHAB is on now, has changed the java search function: https://github.com/apache/karaf/blob/karaf-4.1.x/assemblies/features/base/src/main/filtered-resources/resources/bin/inc#L185 and this file is included with the latest version of openHAB.

I asked @kaikreuzer about it previously [here](https://github.com/openhab/openhab-distro/pull/484/files#r132829680), but thinking about it, we should probably update `setenv` and the duplicated functions that are set in `inc`. Since `inc` is called first, I'm assuming the definitions in `setenv` are useless. WDYT?

**Comment by ThomDietrich** [comment] 2017-08-30 12:18
> But it looks like they also agree with you now ;)

Yay 🤗

**Comment by BClark09** [comment] 2017-10-09 14:14
Hi @RREE, the issues you describe should be at least addressed in the snapshots.

Whilst the package does not depend on java installation package, it will still suggest installing it during installation if it does not detect one.

`journalctl -u openhab2`, `./start.sh` or `openhab-cli start` should also correctly report these problems now.

I'm going to close this issue, but please feel free to reopen it if you feel something else needs to be addressed.

**Closed by BClark09** 2017-10-09 14:14 UTC
