### ISSUE TITLE
.persist configuration files opened in /var/lib/openhab2 instead of /etc/openhab2

### ISSUE THREAD

**Issue by metbril** [openhab/openhab-linuxpkg#29] opened 2017-01-29 07:00 UTC
Initially raised by @euphi here:

https://github.com/openhab/openhab-distro/issues/405

> After upgrading to Openhab2 stable (Using ubuntu 16.04.1 LTS), the .persist configuration files (in my case mapdb.persist and rrd4j.persist) have not been found anymore.
Log files show that openhab looks for them in /var/lib/openhab2 instead of /etc/openhab2.
>
> See https://community.openhab.org/t/rrd4j-persist-moved-to-var-lib-openhab2/21191

**Comment by euphi** [comment] 2017-01-29 16:29
I checked again, the problem occured after upgrade from b5 to stable:

From /var/log/apt/history.log:
```
Start-Date: 2017-01-25  20:31:49
Commandline: apt-get install openhab2
Requested-By: ian (1001)
Install: openhab2:armhf (2.0.0-1)
Remove: openhab2-online:armhf (2.0.0~b5)
End-Date: 2017-01-25  20:36:39
```

From /var/log/openhab2/ ( grep rrd4j.persist openhab.log*)
```
openhab.log.5:2017-01-25 16:24:07.264 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
openhab.log.5:2017-01-25 16:25:37.230 [DEBUG] [sistence.internal.PersistenceManager] - Initializing rrd4j persistence service.
openhab.log.5:2017-01-25 20:38:45.376 [ERROR] [urce.impl.DefaultResourceDescription] - /var/lib/openhab2/rrd4j.persist (No such file or directory)
openhab.log.5:java.io.FileNotFoundException: /var/lib/openhab2/rrd4j.persist (No such file or directory)
openhab.log.5:2017-01-25 20:38:45.377 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'
openhab.log.5:2017-01-25 20:38:45.400 [WARN ] [el.core.internal.ModelRepositoryImpl] - Configuration model 'rrd4j.persist' is either empty or cannot be parsed correctly!
openhab.log.5:2017-01-26 00:11:52.823 [INFO ] [el.core.internal.ModelRepositoryImpl] - Loading model 'rrd4j.persist'

```

(I symlinked /etc/openhab2/persist/*.persist  to /var/lib/openhab2/ just before the restart at 2017-01-26 00:11)

**Comment by euphi** [comment] 2017-01-29 16:31
I there anything I can check to provide more information? Where does openhab2 look for the the path for the .persist file?

Other configuration files are working fine (items, rules, services, transform, sitemaps are in use without any problems).

**Comment by theoweiss** [comment] 2017-01-29 17:33
Give me a hint.

**Comment by BClark09** [comment] 2017-02-24 12:53
Hi @rtvb and @euphi, I was still unable to replicate this. Is this problem still occurring for you both?

**Comment by euphi** [comment] 2017-02-25 07:18
There was no change/update to the stable package, so the problem still occurs.

To have same progress, it would be helpful to know how openhab2 determines the path of its .persist configuration files.

**Comment by BClark09** [comment] 2017-02-25 14:23
> To have same progress, it would be helpful to know how openhab2 determines the path of its .persist configuration files.

Honestly, I'm not sure. It's not something that's specifically set for the package. @kaikreuzer would you be able to shed light on why rrd4j is looking in a different place than other persistence services?

**Comment by euphi** [comment] 2017-02-26 08:00
@BClark09: All .persist file are only found in /var/lib/openhab2.

In my case, these are mapdb.persist and rrd4j.persist only, because no other persistence services are installed.

**Comment by BClark09** [comment] 2017-02-26 12:58
And I simply can't replicate that problem... For me, on a new install and on my full system mapdb.persis and rrd4j.persist only work if they're in /etc/openhab2/persistance, where it is expected they will be.

Note nothing in my /var/lib/openhab2
![image](https://cloud.githubusercontent.com/assets/8983584/23339862/ec04b17e-fc22-11e6-8c27-ead97e90e6ec.png)

But when I change the files inside /etc/openhab2/persistance:
![image](https://cloud.githubusercontent.com/assets/8983584/23339872/2aef1564-fc23-11e6-86ab-c7fced9ab53b.png)


![image](https://cloud.githubusercontent.com/assets/8983584/23339840/96e811f4-fc22-11e6-85ff-220dcd23702d.png)

**Comment by BClark09** [comment] 2017-05-28 23:13
Hi @euphi and @metbril, since I'm still unable to replicate this problem I'm going to close this issue for now. Can you let me know if you have any replication steps or new information, and I can open this issue again.

**Closed by BClark09** 2017-05-28 23:13 UTC

**Comment by euphi** [comment] 2017-05-30 15:08
Mhm. Unfortunately no one answered my question, where openhab stores its config path, so I was not able to investigate further.
I assume there was something special in my upgrade path, so that this configuration (whereever it persisted) was wrong.

For myself,the problem is solved, because I reinstalled my complete server (for other reasons), so the config is now read correctly from /etc/openhab.

I still have the backup of the old installation (complete root-filesystem of the Linaro installation), so I could look up something, if someone told me what to look up and where.

**Comment by BClark09** [comment] 2017-05-30 19:29
Hi @euphi, glad you have if sorted. Quite honestly, I wouldn't know where that specific path for persistence  is written but I do know that it uses the `OPENHAB_CONF` folder prefix. This is set using a file called [oh2_dir_layout](https://github.com/openhab/openhab-linuxpkg/blob/master/resources/deb/bin/oh2_dir_layout) and goes in `/usr/share/openhab2`.
